<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Author;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class AuthorController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        $query = Author::query();

        if ($request->filled('search')) {
            $search = $request->search;
            $query->where('name', 'like', "%{$search}%")
                  ->orWhere('biography', 'like', "%{$search}%");
        }

        $authors = $query->orderBy('name')->paginate(15);

        return view('admin.authors.index', compact('authors'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('admin.authors.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'name' => 'required|string|max:255',
            'full_name' => 'nullable|string|max:255',
            'biography' => 'nullable|string',
            'birth_date' => 'nullable|date',
            'death_date' => 'nullable|date',
            'nationality' => 'nullable|string|max:100',
            'photo' => 'nullable|image|max:2048', // 2MB Max
        ]);

        if ($request->hasFile('photo')) {
            $path = $request->file('photo')->store('authors', 'public');
            $validated['photo_url'] = Storage::url($path);
        }

        // Slug is auto-generated by Model boot method if empty
        
        Author::create($validated);

        return redirect()->route('admin.authors.index')
            ->with('success', 'Autor criado com sucesso!');
    }

    /**
     * Display the specified resource.
     */
    public function show(Author $author)
    {
        return view('admin.authors.show', compact('author'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Author $author)
    {
        return view('admin.authors.edit', compact('author'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Author $author)
    {
        $validated = $request->validate([
            'name' => 'required|string|max:255',
            'full_name' => 'nullable|string|max:255',
            'biography' => 'nullable|string',
            'birth_date' => 'nullable|date',
            'death_date' => 'nullable|date',
            'nationality' => 'nullable|string|max:100',
            'photo' => 'nullable|image|max:2048',
        ]);

        if ($request->hasFile('photo')) {
            // Delete old photo if exists
            if ($author->photo_url) {
                $oldPath = str_replace('/storage/', '', $author->photo_url);
                Storage::disk('public')->delete($oldPath);
            }

            $path = $request->file('photo')->store('authors', 'public');
            $validated['photo_url'] = Storage::url($path);
        }

        $author->update($validated);

        return redirect()->route('admin.authors.index')
            ->with('success', 'Autor atualizado com sucesso!');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Author $author)
    {
        if ($author->books()->exists()) {
            return back()->with('error', 'Não é possível excluir este autor pois ele possui livros vinculados.');
        }

        if ($author->photo_url) {
            $oldPath = str_replace('/storage/', '', $author->photo_url);
            Storage::disk('public')->delete($oldPath);
        }

        $author->delete();

        return redirect()->route('admin.authors.index')
            ->with('success', 'Autor excluído com sucesso!');
    }
}
